### ISSUE TITLE
Help, dotenv is causing issues

### ISSUE THREAD

**Issue by rzcodes** [imanaspaul/Django-eCommerce-tutorial-manascode#7]
I did all of the necessary steps. But it's just not running because load_dotenv is not installing on my computer. 

What's the possible solution, please reply asap. Need to submit my project tomo!!!

**Comment by imanaspaul** [comment]
Please share your errors over here @rzcodes

**Comment by roshanzameer01** [comment]
![159105808-4dd5ea5f-4e88-4a1c-ad50-d79c4b1e1c43](https://user-images.githubusercontent.com/50450052/159217103-e568feb5-ee41-43b0-a32e-4f3e5d20e049.png)

Here you go!
Getting this error after installing dot env. I somehow installed dotenv, noe getting this error

Can you please help me resolve thi issue personally by connecting with me on what's app?

**Comment by rzcodes** [comment]
Hey @imanaspaul Any update on the above?

**Comment by rzcodes** [comment]
Help brotha, I need it URGENTLY!!

**Comment by imanaspaul** [comment]
You need to install crispy forms

```sh
pip install django-crispy-forms
```

**Comment by imanaspaul** [comment]
I hope this helps you, if you have further queries please feel free to create another issue.
